add_noise: True
metrics: ['ilniqe', 'hyperiqa']
corruption_types: ['gaussian_noise']
img_path: '../../../sample_imgs/1.png'
img_name: '1.png'
output_dir: 'output/debug/'
results_path: 'output/debug/debug_results.json'