add_noise: False

# clipiqa+_vitL14_512 model doesn't seem to work. Can't load it in. It loops forever.
# I also get problems running clipiqa+, entropy, hyperiqa, laion_aes, musiq, musiq-ava,
# musiq-paq2piq, musiq-spaq, paq2piq
# qalign takes too much memory, perhaps qalign can be used in Google Colab.
# qalign_4bit and qalign_8bit causes problems with CUDA. 
# I don't think fid can be used as it requires a set of ground truth images
# inception_score: TypeError: only integer tensors of a single element can be converted to an index
metrics: ['wadiqam_nr', 'ilniqe', 'hyperiqa', 'arniqa-clive', 'arniqa-csiq', 'arniqa-flive', 
                'arniqa-kadid', 'arniqa-live', 'arniqa-spaq', 
                'arniqa-tid', 'brisque_matlab', 'clipiqa', 'clipiqa+', 
                'clipiqa+_rn50_512', 'dbcnn', 'cnniqa', 'liqe', 'liqe_mix',
                'maniqa', 'maniqa-kadid', 'maniqa-pipal', 
                'nima', 'nima-koniq', 'nima-spaq', 'nima-vgg16-ava', 'niqe', 
                'niqe_matlab', 'nrqm', 'pi', 'piqe',
                'topiq_iaa', 'topiq_iaa_res50', 'topiq_nr', 
                'topiq_nr-flive', 'topiq_nr-spaq', 'tres', 'tres-flive', 'unique']
img_dir: "../../../sample_imgs"
output_dir: "output/corrupted/"
file_types: [".jpg", ".jpeg", ".png"]