randomness_seed: 5
base_path: "../../../data/tmp/avl-snow-day/dgt_2025-01-08-14-37-21_0_s0/RTB_Camera_Front"
num_images: 10
# Generate images with all possible combinations of distortions
use_combinations: False
n_configs: &n_configs 4
# Select num_images random images from the base_path directory
select_random_imgs_from_base_path: True

blur:
  # blur_value is calculated such that each odd number in between [s, e] INCLUDING
  # s and e will be used. So we'll get images with s, s + 2, s + 4 ... e levels of blur.
  # This has to be odd due to internals of Albumentations.
  # Starts with 3 as lower values get converted to 3.
  # [start, stop, step]. stop is inclusive here.
  blur_value: [3, 51, 4]
  output_dir: "output/albumentations/0_100_blur/blur"
