add_noise: True
# I can't get wadiqam_nr to work. It freezes forever. Might be problem with caching.
metrics: ['ilniqe', 'hyperiqa', 'arniqa-clive', 'arniqa-csiq', 'arniqa-flive', 
                'arniqa-kadid', 'arniqa-live', 'arniqa-spaq', 
                'arniqa-tid', 'brisque_matlab', 'clipiqa', 'clipiqa+', 
                'clipiqa+_rn50_512', 'dbcnn', 'cnniqa', 'liqe', 'liqe_mix',
                'maniqa', 'maniqa-kadid', 'maniqa-pipal', 
                'nima', 'nima-koniq', 'nima-spaq', 'nima-vgg16-ava', 'niqe', 
                'niqe_matlab', 'nrqm', 'pi', 'piqe',
                'topiq_iaa', 'topiq_iaa_res50', 'topiq_nr', 
                'topiq_nr-flive', 'topiq_nr-spaq', 'tres', 'tres-flive', 'unique']

corruption_types: ['gaussian_noise', 'motion_blur', 'defocus_blur']
img_path: '../../../sample_imgs/1.png'
img_name: '1.png'
output_dir: 'output/corrupted/'
results_path: 'output/corrupted/results.json'