# This file is for running metrics that couldn't previously be run
# clipiqa+_vitL14_512 model doesn't seem to work. Can't load it in. It loops forever.
# I also get problems running clipiqa+, entropy, hyperiqa, laion_aes, musiq, musiq-ava,
# musiq-paq2piq, musiq-spaq, paq2piq
# qalign takes too much memory, perhaps qalign can be used in Google Colab.
# qalign_4bit and qalign_8bit causes problems with CUDA. 
# I don't think fid can be used as it requires a set of ground truth images
# inception_score: TypeError: only integer tensors of a single element can be converted to an index
metrics: ['qalign']
img_dir: "output/albumentations/rainy"
output_path: "output/albumentations/other_metrics/rainy/results.json"
file_types: [".jpg", ".jpeg", ".png"]