# qalign takes too much memory
metrics: ['wadiqam_nr', 'hyperiqa', 'arniqa-clive', 'arniqa-csiq', 'arniqa-flive',
           'arniqa-kadid', 'arniqa-live', 'arniqa-spaq',
           'arniqa-tid', 'brisque_matlab', 'clipiqa', 'clipiqa+',
           'clipiqa+_rn50_512', 'dbcnn', 'cnniqa', 'liqe',
           'maniqa', 'maniqa-kadid', 'maniqa-pipal',
           'nima', 'nima-koniq', 'nima-spaq', 'nima-vgg16-ava',
           'nrqm', 'piqe',
           'topiq_iaa', 'topiq_iaa_res50', 'topiq_nr',
           'topiq_nr-flive', 'topiq_nr-spaq', 'tres', 'tres-flive', 'unique',
           'clipiqa+_vitL14_512', 'entropy', 'laion_aes', 'musiq', 'musiq-ava',
           'musiq-paq2piq', 'musiq-spaq', 'paq2piq', 'ilniqe', 'niqe', 'niqe_matlab',
           'pi']
img_dir: "/content/drive/MyDrive/Skola/Thesis/data/sample_roadview_imgs/"
output_path: "/content/drive/MyDrive/Skola/Thesis/data/sample_roadview_imgs/scores.json"
file_types: [".jpg", ".jpeg", ".png"]
# Should the results be cleared before execution
clear_output: False
# Should new results be appended to existing results
append_res: False